### ISSUE TITLE
cannot find or open ../pytch-webapp/website-layer/layer.zip

### ISSUE THREAD

**Issue by ntquan** [pytchlang/pytch-releases#1]
Hi team,

I have an issue when run `make.sh` to deploy. Could you please take a look ?
# ./make.sh 
Making beta-ga950d832ff72.zip
Logging to build-logs/20231012T075154
Built pytch-webapp layer
Built pytch-tutorials layer
Built pytch-vm layer
Built pytch-website layer
unzip:  cannot find or open ../pytch-webapp/website-layer/layer.zip, ../pytch-webapp/website-layer/layer.zip.zip or ../pytch-webapp/website-layer/layer.zip.ZIP.
unzip:  cannot find or open ../pytch-website/website-layer/layer.zip, ../pytch-website/website-layer/layer.zip.zip or ../pytch-website/website-layer/layer.zip.ZIP.
unzip:  cannot find or open ../pytch-build/website-layer/layer.zip, ../pytch-build/website-layer/layer.zip.zip or ../pytch-build/website-layer/layer.zip.ZIP.
/data/platform_acl/pytch-releases/website-layer/beta-ga950d832ff72.zip

Thanks!

**Comment by bennorth** [comment]
Thanks for the report.  Can you look in the `*.err` and `*.out` files in the build log directory mentioned (`build-logs/20231012T075154`)?  In particular, the `*.err` files should contain clues as to what went wrong.

**Comment by ntquan** [comment]
Thank you for your response. This is the log output
`# ls -lrt
total 24
-rw-r--r-- 1 root root    0 Oct 12 07:51 pytch-webapp.out
-rw-r--r-- 1 root root    0 Oct 12 07:51 pytch-tutorials.out
-rw-r--r-- 1 root root   20 Oct 12 07:51 pytch-webapp.err
-rw-r--r-- 1 root root   62 Oct 12 07:51 pytch-tutorials.err
-rw-r--r-- 1 root root  152 Oct 12 07:56 pytch-vm.out
-rw-r--r-- 1 root root 1618 Oct 12 07:56 pytch-vm.err
-rw-r--r-- 1 root root  641 Oct 12 07:56 pytch-website.err
-rw-r--r-- 1 root root 1139 Oct 12 07:56 pytch-website.out


# cat pytch-tutorials.err
Must be run in a clean clone
(no existing poetry environment)


# cat pytch-tutorials.out


# cat pytch-vm.err
npm ERR! code ENETUNREACH
npm ERR! syscall connect
npm ERR! errno ENETUNREACH
npm ERR! request to https://registry.npmjs.org/yargs-unparser/-/yargs-unparser-2.0.0.tgz failed, reason: connect ENETUNREACH 2606:4700::6810:1d22:443

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-10-12T07_51_54_420Z-debug-0.log
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'terser'
Require stack:
- /data/platform_acl/pytch-releases/pytch-vm/support/build/wrapmodules.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/data/platform_acl/pytch-releases/pytch-vm/support/build/wrapmodules.js:3:20)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/platform_acl/pytch-releases/pytch-vm/support/build/wrapmodules.js'
  ]
}

Node.js v18.18.1
website-layer/make.sh: line 28: cd: dist: No such file or directory
cp: target '../website-layer/layer-content/skulpt/a950d832ff72d8e658d1' is not a directory
chmod: missing operand after '644'
Try 'chmod --help' for more information.


# cat pytch-vm.out

> skulpt@1.2.0 prebuild
> node support/build/wrapmodules.js internal

  adding: skulpt/ (stored 0%)
  adding: skulpt/a950d832ff72d8e658d1/ (stored 0%)


# cat pytch-webapp.err
No .env file in src



# cat pytch-webapp.out


# cat pytch-website.err
/data/platform_acl/pytch-releases/pytch-build/makesite/tutorial-asset-credits.sh: line 18: .venv/bin/activate: No such file or directory
/data/platform_acl/pytch-releases/pytch-build/makesite/tutorial-asset-credits.sh: line 24: pytchbuild-gather-asset-credits: command not found
/bin/sh: 1: sphinx-build: not found
make: *** [Makefile:20: html] Error 127
mv: cannot stat 'build/html': No such file or directory
find: 'doc': No such file or directory
chmod: missing operand after '755'
Try 'chmod --help' for more information.
find: 'doc': No such file or directory
chmod: missing operand after '644'
Try 'chmod --help' for more information.



# cat pytch-website.out

  RuntimeError

  The lock file is not compatible with the current version of Poetry.
  Upgrade Poetry to be able to read the lock file or, alternatively, regenerate the lock file with the `poetry lock` command.

  at /usr/lib/python3/dist-packages/poetry/packages/locker.py:481 in _get_lock_data
      477│                 "Upgrade Poetry to ensure the lock file is read properly or, alternatively, "
      478│                 "regenerate the lock file with the `poetry lock` command."
      479│             )
      480│         elif not lock_version_allowed:
    → 481│             raise RuntimeError(
      482│                 "The lock file is not compatible with the current version of Poetry.\n"
      483│                 "Upgrade Poetry to be able to read the lock file or, alternatively, "
      484│                 "regenerate the lock file with the `poetry lock` command."
      485│             )
Working in /data/platform_acl/pytch-releases/pytch-website

Removing old build directory

Rebuilding HTML
	zip warning: name not matched: doc

zip error: Nothing to do! (try: zip -r ../layer.zip . -i doc)`

Thank you for your time.

**Comment by bennorth** [comment]
Thanks for providing that information.  There are quite a lot of error messages there.  What kind of environment are you running this in?  (Which operating system?  Anything unusual about the network?)  Were there any error messages when you set things up with the `develop.sh` script?  Are there clues in the `*-preparation.out` and `*-preparation.err` files (created by `develop.sh`)?

Some thoughts on what the errors might mean:
* `pytch-tutorials.err`: Must be run in a clean clone (no existing poetry environment) — the build script thinks you already have a poetry environment for the pytch-build directory.
* `pytch-vm.err`: npm ERR! code ENETUNREACH [...] request to https://registry.npmjs.org/[...] failed — looks like the build machine can't contact the npm servers to fetch packages required for build
* `pytch-webapp.err`: No .env file in src — there was an oversight in the `develop.sh` script, which was fixed in c5048eeaf5f7, which since your repo is at a950d832ff72, should be included; this suggests something went wrong with the `develop.sh` setup script
* `pytch-website.err`: [...]/tutorial-asset-credits.sh: line 18: .venv/bin/activate: No such file or directory — this is a follow-up failure because it couldn't build the Python env for making the tutorials
* `pytch-website.out`: RuntimeError: The lock file is not compatible with the current version of Poetry — perhaps you have a too-old version of Poetry?

**Comment by ntquan** [comment]
Hi @bennorth,

I'm using Ubuntu 22.04, the network can connect to the internet.
This is the result when I run `develop.sh`
`
`

**Comment by ntquan** [comment]
Hi @bennorth,

Thank you for your response. Based on your information I fixed and checked everything again. I can run the `make.sh` and it is successful.
This is the result:
`
# ./make.sh 
Making beta-ga950d832ff72.zip
Logging to build-logs/20231018T114249
Built pytch-tutorials layer
Built pytch-vm layer
Built pytch-webapp layer
Built pytch-website layer
.../pytch-releases/website-layer/beta-ga950d832ff72.zip
`

Thank you for your time and your help!

**Comment by bennorth** [comment]
Great, I'm glad you were able to sort it out.  If you have questions or feedback about Pytch itself (rather than build or other code issues with the repos), please do get in touch: info@pytch.org
